//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraSeguimiento
    {
        public int Id { get; set; }
        public int IdIncidencia { get; set; }
        public string Evidencia { get; set; }
    
        public virtual Incidencia Incidencia { get; set; }
    }
}
