//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Incidencia()
        {
            this.BitacoraSeguimiento = new HashSet<BitacoraSeguimiento>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdEstado { get; set; }
        public int IdRecursosDigitales { get; set; }
        public string Descripcion { get; set; }
        public int IdSupervisor { get; set; }
        public int ICliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraSeguimiento> BitacoraSeguimiento { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual RecursoDigital RecursoDigital { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
